src/authentication/urls.py
from django.urls import path
from .views import LoginView, LogoutView, SignUpView, UpdateProfilePictureView

app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('update-profile-picture/', UpdateProfilePictureView.as_view(),
         name='update_profile_picture'),
]

src/blog/urls.py
from django.urls import path
from .views import HomeView, PhotoUploadView, CreateBlogPostView, \
    BlogPostListView, BlogPostDetailView

app_name = 'blog'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('upload-photo/', PhotoUploadView.as_view(), name='photo_upload'),
    path('create-blog/', CreateBlogPostView.as_view(), name='create_blog'),
    path('blogposts/', BlogPostListView.as_view(), name='blog_post_list'),
    path('blogpost/<int:pk>/', BlogPostDetailView.as_view(),
         name='blog_post_detail')
]

src/fotoblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('blog/', include('blog.urls')),
] + static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    CREATOR = 'CREATOR'
    SUBSCRIBER = 'SUBSCRIBER'

    ROLE_CHOICES = (
        (CREATOR, 'Creator'),
        (SUBSCRIBER, 'Subscriber'),
    )

    profile_photo = models.ImageField()
    role = models.CharField(max_length=30, choices=ROLE_CHOICES)

src/blog/models.py
from django.db import models
from django.conf import settings

class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=128,
                               blank=True)
    uploader = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                                 on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

class Blog(models.Model):
    photo = models.ForeignKey(to=Photo,
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    starred = models.BooleanField(default=False)

src/authentication/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

class SignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'role')

class UpdateProfilePictureForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UpdateProfilePictureForm, self).__init__(*args, **kwargs)
        self.fields['profile_photo'].widget.attrs.update({
            'onchange': "preview();"
        })
        #self.fields['profile_photo'].widget.initial_text = 'Current'
        #self.fields['profile_photo'].widget.input_text = 'Select photo'

    class Meta:
        model = get_user_model()
        fields = ('profile_photo',)

src/blog/forms.py
from django import forms
from .models import Photo, Blog

class PhotoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PhotoForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs['onchange'] = 'preview();'

    class Meta:
        model = Photo
        fields = ('image', 'caption')

class BlogForm(forms.ModelForm):
    edit = forms.BooleanField(initial=True)

    class Meta:
        model = Blog
        fields = ('title', 'content')
        widgets = {
            'content': forms.Textarea(attrs={
                'cols': 50, 'rows': 10
            }),
            'edit': forms.HiddenInput
        }

class DeleteBlogForm(forms.Form):
    delete = forms.BooleanField(initial=True)

    class Meta:
        widgets = {
            'delete': forms.HiddenInput
        }

src/authentication/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import get_user_model
from django.views.generic import View
from django.views.generic.edit import UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import SignUpForm, UpdateProfilePictureForm

class LoginView(LoginView):
    template_name = 'authentication/login.html'
    redirect_authenticated_user = True

class LogoutView(LogoutView):
    template_name = None

class SignUpView(View):
    form_class = SignUpForm
    template_name = 'authentication/signup.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name,
                      context={'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('authentication:login')
        return render(request, self.template_name,
                      context={'form': form})

class UpdateProfilePictureView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UpdateProfilePictureForm
    template_name = 'authentication/update_profile_picture.html'
    success_url = reverse_lazy('blog:home')

    def get_object(self, queryset=None):
        return self.request.user

src/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .forms import PhotoForm, BlogForm
from .models import Photo, Blog

class HomeView(LoginRequiredMixin, ListView):
    model = Photo
    context_object_name = 'photos'
    template_name = 'blog/home.html'

class PhotoUploadView(LoginRequiredMixin, View):
    form_class = PhotoForm
    template_name = 'blog/photo_upload.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name,
                      context={'form': form})

    def post(self, request):
        form = self.form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            return redirect('blog:home')
        return render(request, self.template_name,
                      context={'form': form})

class CreateBlogPostView(LoginRequiredMixin, View):
    photo_form = PhotoForm
    blog_form = BlogForm
    template_name = 'blog/create_blog_post.html'

    def get(self, request):
        photo_form = self.photo_form()
        blog_form = self.blog_form()
        return render(request, self.template_name,
                      context={'photo_form': photo_form,
                               'blog_form': blog_form})

    def post(self, request):
        photo_form = self.photo_form(request.POST, request.FILES)
        blog_form = self.blog_form(request.POST)
        if all([photo_form.is_valid(), blog_form.is_valid()]):
            photo = photo_form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            blog_post = blog_form.save(commit=False)
            blog_post.photo = photo
            blog_post.author = request.user
            blog_post.save()
            return redirect('blog:home')
        return render(request, self.template_name,
                      context={'photo_form': photo_form,
                               'blog_form': blog_form})

class BlogPostListView(LoginRequiredMixin, ListView):
    model = Blog
    context_object_name = 'blog_posts'
    template_name = 'blog/blog_post_list.html'

class BlogPostDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    context_object_name = 'blog_post'
    template_name = 'blog/blog_post_detail.html'

src/authentication/templates/authentication/login.html
{% extends 'base.html' %}

{% block content %}
<h3>Log In</h3>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<p>Not a member? <a href="{% url 'authentication:signup' %}">Sign up</a> now!</p>
{% endblock content %}

src/authentication/templates/authentication/signup.html
{% extends 'base.html' %}

{% block content %}
<h3>Sign Up</h3>
{% if form.errors %}
    {{ form.errors }}
{% endif %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
<p>Already a member? <a href="{% url 'authentication:login' %}">Login</a>.</p>
{% endblock content %}

src/authentication/templates/authentication/update_profile_picture.html
{% extends 'base.html' %}

{% block content %}
<h3>Update Profile Picture</h3>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <img id="preview-image" width="120px"><br><br>
    <button type="submit">Submit</button>
</form>
{% endblock content %}

src/blog/templates/blog/blog_post_detail.html
{% extends 'base.html' %}

{% block content %}
<h3>{{ blog_post.title }}</h3>
<div>
    <small><strong>Author:</strong> {{ blog_post.author.username }}</small> &bull;
    <small><strong>Date created:</strong> {{ blog_post.date_created }}</small>
</div>
<hr>
<p>{{ blog_post.content }}</p>
<figure>
    <img src="{{ blog_post.photo.image.url }}" width="250px" alt="">
    <figcaption><small>{{ blog_post.photo.caption }}</small></figcaption>
</figure>
<hr>
<small><strong>Last updated:</strong> {{ blog_post.last_updated }}</small>
{% endblock content %}

src/blog/templates/blog/blog_post_list.html
{% extends 'base.html' %}

{% block content %}
<h3>Blog posts</h3>
{% for blog_post in blog_posts %}
    <ul>
        <li><a href="{% url 'blog:blog_post_detail' blog_post.id %}">{{ blog_post.title }}</a></li>
    </ul>
{% endfor %}
{% endblock content %}

src/blog/templates/blog/create_blog_post.html
{% extends 'base.html' %}

{% block content %}
<h3>Create blog post</h3>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ blog_form.as_p }}
    {{ photo_form.as_p }}
    <img id="preview-image" width="150px"><br><br>
    <button type="submit">Submit</button>
</form>
{% endblock content %}

src/blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
<p class="welcome-text">Hello {{ user.username }}! Welcome back.</p>
<h3>Photos</h3>
<div class="grid">
    {% for photo in photos %}
    <img src="{{ photo.image.url }}" title="{{ photo.caption }}">
    {% endfor %}
</div>
{% endblock content %}

src/blog/templates/blog/photo_upload.html
{% extends 'base.html' %}

{% block content %}
<h3>Upload a Photo</h3>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endblock content %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FotoBlog</title>
    <link rel="icon" href="{% static 'image/favicon.png' %}" />
    {# Masonry layout CSS #}
    <link rel="stylesheet" href="https://unpkg.com/flexmasonry/dist/flexmasonry.css">
    {# Custom CSS #}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {# Google font CSS #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap">
</head>
<body>
    <div class="main">
        <div class="left-section">
            <img class="site-logo" src="{% static 'image/favicon.png' %}" alt="FotoBlog site logo">
            <h1 class="site-heading">FotoBlog</h1>
            <hr>
            {% if user.is_authenticated %}
                <div id="user-profile-picture">
                    {% if request.user.profile_photo %}
                        <img class="avatar" src="{{ request.user.profile_photo.url }}" alt="User's profile picture">
                    {% else %}
                        <img class="avatar" src="{% static 'image/default-profile-picture.png' %}" alt="Default profile picture">
                    {% endif %}
                    <a href="{% url 'authentication:update_profile_picture' %}"><img src="{% static 'image/edit-profile-picture.png' %}" width="18px" title="Update profile picture"></a>
                </div>
                <div id="navbar" class="nav-links">
                    <a href="{% url 'blog:home' %}">Photo feed</a>
                    <a href="{% url 'blog:photo_upload' %}">Upload photo</a>
                    <a href="{% url 'blog:create_blog' %}">Create blog post</a>
                    <a href="{% url 'blog:blog_post_list' %}">Blog posts</a>
                    <a href="{% url 'authentication:logout' %}">Logout</a>
                </div>
            {% endif %}
        </div>
        <div class="right-section">
            {% block content %}
            {# page content goes here ... #}
            {% endblock content %}
        </div>
    </div>
    <script src="https://unpkg.com/flexmasonry/dist/flexmasonry.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/preview-image.js' %}"></script>
</body>
</html>